# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'

target 'Throttled' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'WKZombie', '~> 1.0'
  pod 'Erik'

  target 'Throttled-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThrottledTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
